### PR TITLE
feat: add support for organization's readme

### LINKED ISSUE #2: Support org readme
Would be great to be able to just type the org name and get the repo (like https://github.com/op-ent). I guess it could be archived. I guess it would be fetched like so: `https://github.com/${org}/.github/blob/main/profile/README.md`

### PR DESCRIPTION
**Pull request by florian-lefebvre**
Close #2 cc @Atinux

### CODE REVIEW

**Comment by Atinux** [comment]
Does it work when typing only the name of the org and hitting enter?

**Comment by florian-lefebvre** [comment]
I only added the file on GitHub but I just tried setting up the fork locally and couldn't get the app running. I'm getting the following error: `Package import specifier "#imports" is not defined in package` (I'm on Windows). Looks like it's related to https://github.com/nuxt/framework/issues/5257 and https://github.com/nuxt/framework/pull/5461 but I guess they're only available on the edge version.
I'm going to debug this to get it running and I'll be back.

**Comment by florian-lefebvre** [comment]
Still getting the error, I created an issue https://github.com/nuxt/framework/issues/10126

**Comment by florian-lefebvre** [comment]
Hey @Atinux it's working now (example at https://nuxt-typo-readme-aonclhnfw-atinux.vercel.app/op-ent, typing in the search bar also works)

**Comment by atinux** [comment]
Awesome!

**Pull request merged**
